layout_spectrum: 0.02656649868004024
typography_spectrum: 0.005441012559458613
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.9485985322389752
  lightness: 0.13579557556658983
  saturation: 0.5179722227621824
  rhythmicContrast: 0.8488539266400039
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: BajandoFino
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9699efc6-f71b-40ae-b0b4-1bd55b5cb175.png
title: Bajando Fino
description: Merengue
purpose:
  - type: contact
    url: 'mailto:gtorres@go-latino.com'
    label: Booking
  - type: external
    url: 'http://www.cdbaby.com/Artist/XavieryBajandoFino'
    label: Music Store
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FzXOPojhYEwc%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DzXOPojhYEwc&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FzXOPojhYEwc%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: GO-LATINO RECORDS
          url: 'https://www.youtube.com/user/golatino0708'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - merengue
        - electronico
        - musica
        - mambo
        - swing
        - bajandofino
        - golatino
        - latin
        - tropical
        - grammys
        - billboards
      description: >-
        UNA NOCHE MAS - Bajando Fino - Raw Video "Unofficial Video" Modelo:
        Germania Martinez AF Films Alberto Flash
        http://www.cdbaby.com/cd/xavierybajandofinoxbf Una noche mas, marca el
        comienzo de una aventura musical llena de ritmo, lirica y fusion de
        ritmos para Xavier Bajando Fino.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=zXOPojhYEwc'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=zXOPojhYEwc
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=zXOPojhYEwc
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=zXOPojhYEwc'
      title: UNA NOCHE MAS - Bajando Fino - Raw Video "Unofficial Video"
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FzXOPojhYEwc%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DzXOPojhYEwc&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FzXOPojhYEwc%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: GO-LATINO RECORDS
          url: 'https://www.youtube.com/user/golatino0708'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - merengue
        - electronico
        - musica
        - mambo
        - swing
        - bajandofino
        - golatino
        - latin
        - tropical
        - grammys
        - billboards
      description: >-
        UNA NOCHE MAS - Bajando Fino - Raw Video "Unofficial Video" Modelo:
        Germania Martinez AF Films Alberto Flash
        http://www.cdbaby.com/cd/xavierybajandofinoxbf Una noche mas, marca el
        comienzo de una aventura musical llena de ritmo, lirica y fusion de
        ritmos para Xavier Bajando Fino.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=zXOPojhYEwc'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=zXOPojhYEwc
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=zXOPojhYEwc
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=zXOPojhYEwc'
      title: UNA NOCHE MAS - Bajando Fino - Raw Video "Unofficial Video"
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FzXOPojhYEwc%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DzXOPojhYEwc&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FzXOPojhYEwc%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: GO-LATINO RECORDS
          url: 'https://www.youtube.com/user/golatino0708'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - merengue
        - electronico
        - musica
        - mambo
        - swing
        - bajandofino
        - golatino
        - latin
        - tropical
        - grammys
        - billboards
      description: >-
        UNA NOCHE MAS - Bajando Fino - Raw Video "Unofficial Video" Modelo:
        Germania Martinez AF Films Alberto Flash
        http://www.cdbaby.com/cd/xavierybajandofinoxbf Una noche mas, marca el
        comienzo de una aventura musical llena de ritmo, lirica y fusion de
        ritmos para Xavier Bajando Fino.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=zXOPojhYEwc'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=zXOPojhYEwc
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=zXOPojhYEwc
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=zXOPojhYEwc'
      title: UNA NOCHE MAS - Bajando Fino - Raw Video "Unofficial Video"
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FzXOPojhYEwc%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DzXOPojhYEwc&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FzXOPojhYEwc%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: GO-LATINO RECORDS
          url: 'https://www.youtube.com/user/golatino0708'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - merengue
        - electronico
        - musica
        - mambo
        - swing
        - bajandofino
        - golatino
        - latin
        - tropical
        - grammys
        - billboards
      description: >-
        UNA NOCHE MAS - Bajando Fino - Raw Video "Unofficial Video" Modelo:
        Germania Martinez AF Films Alberto Flash
        http://www.cdbaby.com/cd/xavierybajandofinoxbf Una noche mas, marca el
        comienzo de una aventura musical llena de ritmo, lirica y fusion de
        ritmos para Xavier Bajando Fino.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=zXOPojhYEwc&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=zXOPojhYEwc'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=zXOPojhYEwc
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=zXOPojhYEwc
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=zXOPojhYEwc'
      title: UNA NOCHE MAS - Bajando Fino - Raw Video "Unofficial Video"
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/4799aeed-0ade-4745-8fdc-d954d00287ad.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/4799aeed-0ade-4745-8fdc-d954d00287ad.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/0ce43d30-9545-47a9-b55f-374a67ee9e15.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/0ce43d30-9545-47a9-b55f-374a67ee9e15.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
author:
  name: Geovanny Torres
  email: gtorres@actionletter.com
  url: 'http://www.golatinorecords.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/657ade5e-3e1b-44ef-b10a-f569d4ec0917.png
