name: BajandoFino
favicon: null
layout_spectrum: 0.45174008095636964
typography_spectrum: 0.6559706323314458
title: Bajando Fino - Orquesta de Merengue y Musica Tropical
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c1010'
    - '#59543d'
    - '#901e18'
    - '#ababab'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
