name: BajandoFino
favicon: null
layout_spectrum: 0.45174008095636964
typography_spectrum: 0.6559706323314458
title: Bajando Fino - Orquesta de Merengue y Musica Tropical
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070d0e'
    - '#61654f'
    - '#b6b6b6'
    - '#8e1e19'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
